/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs.index'
import { Route as ProgramsSlugRouteImport } from './routes/programs.$slug'
import { Route as LpBscNursingSecureCareerRouteImport } from './routes/lp.bsc-nursing-secure-career'
import { Route as LpBscNursingNeetAlternativeRouteImport } from './routes/lp.bsc-nursing-neet-alternative'
import { Route as LpBscNursingDirectRouteImport } from './routes/lp.bsc-nursing-direct'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'
import { Route as ApiPublicApplicationsRouteImport } from './routes/api/public/applications'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsSlugRoute = ProgramsSlugRouteImport.update({
  id: '/programs/$slug',
  path: '/programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LpBscNursingSecureCareerRoute =
  LpBscNursingSecureCareerRouteImport.update({
    id: '/lp/bsc-nursing-secure-career',
    path: '/lp/bsc-nursing-secure-career',
    getParentRoute: () => rootRouteImport,
  } as any)
const LpBscNursingNeetAlternativeRoute =
  LpBscNursingNeetAlternativeRouteImport.update({
    id: '/lp/bsc-nursing-neet-alternative',
    path: '/lp/bsc-nursing-neet-alternative',
    getParentRoute: () => rootRouteImport,
  } as any)
const LpBscNursingDirectRoute = LpBscNursingDirectRouteImport.update({
  id: '/lp/bsc-nursing-direct',
  path: '/lp/bsc-nursing-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApplicationsRoute = ApiPublicApplicationsRouteImport.update({
  id: '/api/public/applications',
  path: '/api/public/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/lp/bsc-nursing-direct': typeof LpBscNursingDirectRoute
  '/lp/bsc-nursing-neet-alternative': typeof LpBscNursingNeetAlternativeRoute
  '/lp/bsc-nursing-secure-career': typeof LpBscNursingSecureCareerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/lp/bsc-nursing-direct': typeof LpBscNursingDirectRoute
  '/lp/bsc-nursing-neet-alternative': typeof LpBscNursingNeetAlternativeRoute
  '/lp/bsc-nursing-secure-career': typeof LpBscNursingSecureCareerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs': typeof ProgramsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admissions': typeof AdmissionsRoute
  '/apply': typeof ApplyRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/lp/bsc-nursing-direct': typeof LpBscNursingDirectRoute
  '/lp/bsc-nursing-neet-alternative': typeof LpBscNursingNeetAlternativeRoute
  '/lp/bsc-nursing-secure-career': typeof LpBscNursingSecureCareerRoute
  '/programs/$slug': typeof ProgramsSlugRoute
  '/programs/': typeof ProgramsIndexRoute
  '/api/public/applications': typeof ApiPublicApplicationsRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/campus-life'
    | '/contact'
    | '/lp/bsc-nursing-direct'
    | '/lp/bsc-nursing-neet-alternative'
    | '/lp/bsc-nursing-secure-career'
    | '/programs/$slug'
    | '/programs/'
    | '/api/public/applications'
    | '/api/public/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/campus-life'
    | '/contact'
    | '/lp/bsc-nursing-direct'
    | '/lp/bsc-nursing-neet-alternative'
    | '/lp/bsc-nursing-secure-career'
    | '/programs/$slug'
    | '/programs'
    | '/api/public/applications'
    | '/api/public/leads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admissions'
    | '/apply'
    | '/campus-life'
    | '/contact'
    | '/lp/bsc-nursing-direct'
    | '/lp/bsc-nursing-neet-alternative'
    | '/lp/bsc-nursing-secure-career'
    | '/programs/$slug'
    | '/programs/'
    | '/api/public/applications'
    | '/api/public/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ApplyRoute: typeof ApplyRoute
  CampusLifeRoute: typeof CampusLifeRoute
  ContactRoute: typeof ContactRoute
  LpBscNursingDirectRoute: typeof LpBscNursingDirectRoute
  LpBscNursingNeetAlternativeRoute: typeof LpBscNursingNeetAlternativeRoute
  LpBscNursingSecureCareerRoute: typeof LpBscNursingSecureCareerRoute
  ProgramsSlugRoute: typeof ProgramsSlugRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  ApiPublicApplicationsRoute: typeof ApiPublicApplicationsRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$slug': {
      id: '/programs/$slug'
      path: '/programs/$slug'
      fullPath: '/programs/$slug'
      preLoaderRoute: typeof ProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/bsc-nursing-secure-career': {
      id: '/lp/bsc-nursing-secure-career'
      path: '/lp/bsc-nursing-secure-career'
      fullPath: '/lp/bsc-nursing-secure-career'
      preLoaderRoute: typeof LpBscNursingSecureCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/bsc-nursing-neet-alternative': {
      id: '/lp/bsc-nursing-neet-alternative'
      path: '/lp/bsc-nursing-neet-alternative'
      fullPath: '/lp/bsc-nursing-neet-alternative'
      preLoaderRoute: typeof LpBscNursingNeetAlternativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/bsc-nursing-direct': {
      id: '/lp/bsc-nursing-direct'
      path: '/lp/bsc-nursing-direct'
      fullPath: '/lp/bsc-nursing-direct'
      preLoaderRoute: typeof LpBscNursingDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/applications': {
      id: '/api/public/applications'
      path: '/api/public/applications'
      fullPath: '/api/public/applications'
      preLoaderRoute: typeof ApiPublicApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdmissionsRoute: AdmissionsRoute,
  ApplyRoute: ApplyRoute,
  CampusLifeRoute: CampusLifeRoute,
  ContactRoute: ContactRoute,
  LpBscNursingDirectRoute: LpBscNursingDirectRoute,
  LpBscNursingNeetAlternativeRoute: LpBscNursingNeetAlternativeRoute,
  LpBscNursingSecureCareerRoute: LpBscNursingSecureCareerRoute,
  ProgramsSlugRoute: ProgramsSlugRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  ApiPublicApplicationsRoute: ApiPublicApplicationsRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
